package com.hs.eai.jobsoverview.model;

// Generated 2-jul-2012 15:30:42 by Hibernate Tools 3.4.0.CR1

/**
 * JobPartMonitor generated by hbm2java
 */
@SuppressWarnings("serial")
public class JobPartMonitor implements java.io.Serializable {

	private int id;
	private JobPart jobPart;
	private JobStatus jobStatus;
	private int errorThresholdMinutes;
	private boolean active;

	public JobPartMonitor() {
	}

	public JobPartMonitor(int id, JobPart jobPart, JobStatus jobStatus,
			int errorThresholdMinutes, boolean active) {
		this.id = id;
		this.jobPart = jobPart;
		this.jobStatus = jobStatus;
		this.errorThresholdMinutes = errorThresholdMinutes;
		this.active = active;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public JobPart getJobPart() {
		return this.jobPart;
	}

	public void setJobPart(JobPart jobPart) {
		this.jobPart = jobPart;
	}

	public JobStatus getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(JobStatus jobStatus) {
		this.jobStatus = jobStatus;
	}

	public int getErrorThresholdMinutes() {
		return this.errorThresholdMinutes;
	}

	public void setErrorThresholdMinutes(int errorThresholdMinutes) {
		this.errorThresholdMinutes = errorThresholdMinutes;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
