package com.hs.eai.jobsoverview.model;

// Generated 2-jul-2012 15:30:42 by Hibernate Tools 3.4.0.CR1

/**
 * JobTypeDependancy generated by hbm2java
 */
@SuppressWarnings("serial")
public class JobTypeDependancy implements java.io.Serializable {

	private int id;
	private JobType jobTypeByJobTypeId;
	private JobType jobTypeByJobTypeIdPrerequisite;
	private boolean active;

	public JobTypeDependancy() {
	}

	public JobTypeDependancy(int id, JobType jobTypeByJobTypeId,
			JobType jobTypeByJobTypeIdPrerequisite, boolean active) {
		this.id = id;
		this.jobTypeByJobTypeId = jobTypeByJobTypeId;
		this.jobTypeByJobTypeIdPrerequisite = jobTypeByJobTypeIdPrerequisite;
		this.active = active;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public JobType getJobTypeByJobTypeId() {
		return this.jobTypeByJobTypeId;
	}

	public void setJobTypeByJobTypeId(JobType jobTypeByJobTypeId) {
		this.jobTypeByJobTypeId = jobTypeByJobTypeId;
	}

	public JobType getJobTypeByJobTypeIdPrerequisite() {
		return this.jobTypeByJobTypeIdPrerequisite;
	}

	public void setJobTypeByJobTypeIdPrerequisite(
			JobType jobTypeByJobTypeIdPrerequisite) {
		this.jobTypeByJobTypeIdPrerequisite = jobTypeByJobTypeIdPrerequisite;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
