package com.hs.eai.jobsoverview.model;

// Generated 2-jul-2012 15:30:42 by Hibernate Tools 3.4.0.CR1

/**
 * NonWorkingDays generated by hbm2java
 */
@SuppressWarnings("serial")
public class NonWorkingDays implements java.io.Serializable {

	private NonWorkingDaysId id;
	private Calendar calendar;
	
	public NonWorkingDays() {
	}

	public NonWorkingDays(NonWorkingDaysId id, Calendar calendar) {
		this.id = id;
		this.calendar = calendar;
	}

	public NonWorkingDaysId getId() {
		return this.id;
	}

	public void setId(NonWorkingDaysId id) {
		this.id = id;
	}

	public Calendar getCalendar() {
		return this.calendar;
	}

	public void setCalendar(Calendar calendar) {
		this.calendar = calendar;
	}

}
