package com.hs.eai.jobsoverview.model;

// Generated 2-jul-2012 15:30:42 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ProcessingDays generated by hbm2java
 */
@SuppressWarnings("serial")
public class ProcessingDays implements java.io.Serializable {

	private int id;
	private String description;
	private boolean active;
	private Set<Calendar> calendars = new HashSet<Calendar>(0);
	private Set<Schedule> schedules = new HashSet<Schedule>(0);

	public ProcessingDays() {
	}

	public ProcessingDays(int id, String description, boolean active) {
		this.id = id;
		this.description = description;
		this.active = active;
	}

	public ProcessingDays(int id, String description, boolean active,
			Set<Calendar> calendars, Set<Schedule> schedules) {
		this.id = id;
		this.description = description;
		this.active = active;
		this.calendars = calendars;
		this.schedules = schedules;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Set<Calendar> getCalendars() {
		return this.calendars;
	}

	public void setCalendars(Set<Calendar> calendars) {
		this.calendars = calendars;
	}

	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

}
