package com.hs.eai.jobsoverview.model;

// Generated 2-jul-2012 15:30:42 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * ServiceSchedule generated by hbm2java
 */
@SuppressWarnings("serial")
public class ServiceSchedule implements java.io.Serializable {

	private int id;
	private Schedule schedule;
	private String description;
	private String serviceName;
	private boolean active;

	public ServiceSchedule() {
	}

	public ServiceSchedule(int id, Schedule schedule, String description,
			String serviceName, boolean active) {
		this.id = id;
		this.schedule = schedule;
		this.description = description;
		this.serviceName = serviceName;
		this.active = active;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Serializable getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
